export const INCREAMENT_QUANTITY = 'INCREAMENT_QUANTITY';
export const DECREAMENT_QUANTITY = 'DECREAMENT_QUANTITY';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const INCREAMENT_DISCOUNT = 'INCREAMENT_DISCOUNT';
export const DECREAMENT_DISCOUNT = 'DECREAMENT_DISCOUNT';
